
//DIALOG CREATE
//for create a dialog send array of id's of users
POST https://localhost:3000/dialogs
content-type: application/json

{
    "dialogParticipants": ["61b20cb998c39ca37a0c41a4", "61b0d186c1e3ffdc2bc6a143"]
}

###

//DIALOG GET
//for get a dialog send its id
GET http://localhost:3000/dialogs/61b0d186c1e3ffdc2bc6a143

###

//DIALOG DELETE
//for delete a dialog send its id
DELETE http://localhost:3000/user/61b0c960c06796c9ca7ac193

###

//USER CREATE
//for create a user send json of email, password and fullname
POST http://localhost:3000/user/registration
content-type: application/json

{
    "email": "test@yandex.com",
    "password": "qwerty",
    "fullname": "Test"
}

###

//USER GET
//for get a user send its id
GET http://localhost:3000/user/61b0d186c1e3ffdc2bc6a143
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvdGludmxhZEB5YW5kZXgucnUiLCJwYXNzd29yZCI6InF3ZXJ0eSIsImlhdCI6MTYzOTgyNDU0MCwiZXhwIjoxNjM5ODI0NTUwfQ.PGISBSol-QJi_kUDtx75S9gPRCbJlusC4FozsOFfwr0

###


//USER DELETE
//for delete a user send its id
DELETE http://localhost:3000/user/61b84fde22cbe0f3a5c57f18

###


//MESSAGE CREATE
//for create a message send json of text, dialogId, userId
POST http://localhost:3000/messages
content-type: application/json

{
    "text": "Hello World you too!",
    "dialogId": "61b8a431868dd6c026c5d50f",
    "userId": "61b20cb998c39ca37a0c41a4"
}

###

//MESSAGE GET
//for get a message send its id
GET http://localhost:3000/messages?id=61b8aa3a296b2b75ffc1fef1
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvdGludmxhZEB5YW5kZXgucnUiLCJwYXNzd29yZCI6InF3ZXJ0eSIsImlhdCI6MTYzOTgyMjUyM30.xqL6R5fB9Eqdz83Pxz3-sbE4GLQ0oL4TxiDY49x3nm8'
###


//MESSAGE DELETE
//for delete a message send its id
DELETE http://localhost:3000/messages?id=61b8aa67296b2b75ffc1fef3

###

//LOGIN 
POST http://localhost:3000/login
content-type: application/json

{
    "email": "test@yandex.com",
    "password": "qwerty"
}