
//DIALOG CREATE
//for create a dialog send array of id's of users
POST https://localhost:3000/dialogs
content-type: application/json

{
    "dialogParticipants": ["61b20cb998c39ca37a0c41a4", "61b0d186c1e3ffdc2bc6a143"]
}

###

//DIALOG GET
//for get a dialog send its id
GET http://localhost:3000/dialogs/61be09993c1163dc6ce207bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAeWFuZGV4LmNvbSIsInBhc3N3b3JkIjoicXdlcnR5IiwiaWF0IjoxNjM5ODQ0MjkwLCJleHAiOjE2NDA0NDkwOTB9.pqnUL2BKes-PuGSCKpPzEOpgYOlul6B6lH7ADq-dvd4

###

//DIALOG DELETE
//for delete a dialog send its id
DELETE http://localhost:3000/user/61b0c960c06796c9ca7ac193

###

//USER CREATE
//for create a user send json of email, password and fullname
POST http://localhost:3000/user/registration
content-type: application/json

{
    "email": "test1@yandex.com",
    "password": "qwerty",
    "fullname": "Test"
}

###

//USER GET
//for get a user send its id
GET http://localhost:3000/user/61be09993c1163dc6ce207bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAeWFuZGV4LmNvbSIsInBhc3N3b3JkIjoicXdlcnR5IiwiaWF0IjoxNjM5ODQ0MjkwLCJleHAiOjE2NDA0NDkwOTB9.pqnUL2BKes-PuGSCKpPzEOpgYOlul6B6lH7ADq-dvd4


###


//USER DELETE
//for delete a user send its id
DELETE http://localhost:3000/user/61be09993c1163dc6ce207bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAeWFuZGV4LmNvbSIsInBhc3N3b3JkIjoicXdlcnR5IiwiaWF0IjoxNjM5ODQ0MjkwLCJleHAiOjE2NDA0NDkwOTB9.pqnUL2BKes-PuGSCKpPzEOpgYOlul6B6lH7ADq-dvd4

###


//MESSAGE CREATE
//for create a message send json of text, dialogId, userId
POST http://localhost:3000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAeWFuZGV4LmNvbSIsInBhc3N3b3JkIjoicXdlcnR5IiwiaWF0IjoxNjQxOTg3NDg1LCJleHAiOjE2NDI1OTIyODV9.R9VTIUUla8_5UWkn-eaxPLU0ZZVCSWx4TVsFSL2peKg
content-type: application/json

{
    "text": "Hello World you too!",
    "dialogId": "61b8a431868dd6c026c5d50f",
    "userId": "61b20cb998c39ca37a0c41a4"
}

###

//MESSAGE GET
//for get a message send its id
GET http://localhost:3000/messages?id=61b0d186c1e3ffdc2bc6a143
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbHlpQHlhbmRleC5jb20iLCJwYXNzd29yZCI6InF3ZXJ0eSIsImlhdCI6MTY0MjI2MzI3MSwiZXhwIjoxNjQyODY4MDcxfQ.onyQ5DUeMYVkVOThFzqB3rS4HSul8WU2afunub2Emgk
###


//MESSAGE DELETE
//for delete a message send its id
DELETE http://localhost:3000/messages?id=61b8aa67296b2b75ffc1fef3

###

//LOGIN 
POST http://localhost:3000/user/login
content-type: application/json

{
    "email": "belyi@yandex.com",
    "password": "qwerty"
}